### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by sspooky13**
Hello,

I "upgraded" your library to supported and maintained repository and I added next PHP versions to Travis build. As said author of [asm89/twig-cache-extension](https://github.com/asm89/twig-cache-extension) that [repository will be deprecated](https://github.com/twigphp/twig-cache-extension/commit/cdea66eccd13d9d20fb745df7d7d7ca7136bd9fa) so I recommend you updated this bundle to supported version.

PS: You have to not accept first commit if you don't want and also you can edit all commits to your wish.

Thank you in advance 🤝

### CODE REVIEW

**Comment by toooni** [comment]
Hi @sspooky13
Thank you for this PR. Looks good to me at first sight. I'll take a closer look tomorrow and will merge it after I've tested it in my codebase.

**Comment by toooni** [comment]
Hi @sspooky13 
I've made some changes here (https://github.com/EmanueleMinotto/TwigCacheBundle/pull/25). Before we can add php7.4 in travis we'll need to update phpunit compatibility.
If you are ok with the changes I will close this PR and merge the other one.

**Comment by sspooky13** [comment]
Hello @toooni,
I am ok with it but you could do changes in this PR. At any rate, changes are important, not PR 😄 so you can close this PR and merge your PR 👍

**Comment by toooni** [comment]
Sorry, I didn't know I could push inside your branch since it's in the sspooky12 namespace. I've made the changes here and closed the other PR. But your commits would still have been preserved.

**Comment by sspooky13** [comment]
Yes, you can push to fork repository if is it allowed. There is no need to apologize, every person is learning whole life 😊.

Anyway, thanks for cooperating 🤝

obrázok

**Pull request merged**
