### PR TITLE
ability to redefine key generator as service

### PR DESCRIPTION
**Pull request by mente**

### CODE REVIEW

**Comment by mente** [comment]
> Couldn't authenticate against github.com

Meh, any ideas how to restart it?

**Comment by EmanueleMinotto** [comment]
Hi @mente, could you please update the [Configuration Reference](https://github.com/EmanueleMinotto/TwigCacheBundle/blob/master/Resources/doc/configuration-reference.rst) in the documentation too?

Thank you for your help :)

**Comment by mente** [comment]
done

**Comment by mente** [comment]
@EmanueleMinotto did you forget about me? :)

**Comment by EmanueleMinotto** [comment]
@mente oops... yes, sorry ^^'
I'll merge your PR this evening, thanks for the reminder

**Pull request merged**
